# Generated by Django 2.2.7 on 2020-01-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200121_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
