# Generated by Django 2.2.7 on 2020-03-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0004_auto_20200314_2238'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
    ]
