# Generated by Django 2.2.7 on 2020-03-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0005_auto_20200314_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='stamps.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='stamps.Group'),
        ),
    ]
