# Generated by Django 2.2.7 on 2020-06-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0008_auto_20200315_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='media/categories'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(upload_to='media/groups'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products'),
        ),
    ]
