# Generated by Django 2.2.7 on 2020-06-06 19:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0009_auto_20200606_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customization_descriptions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('line1', 'Line 1'), ('line2', 'Line 2'), ('line3', 'Line 3')], max_length=17, null=True),
        ),
    ]
