# Generated by Django 2.2.7 on 2020-06-06 23:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0011_auto_20200607_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customization_descriptions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('line1', 'Line 1'), ('line2', 'Line 2'), ('line3', 'Line 3'), ('line4', 'Line 4'), ('line5', 'Line 5'), ('text', 'Text'), ('top-outer-circle-text', 'Top Outer Circle Text'), ('monogram-initial', 'Monogram Initial'), ('center-text', 'Center Text'), ('bottom-outer-circle-text', 'Bottom Outer Circle Text'), ('below-arrow', 'Below Arrow')], max_length=999, null=True),
        ),
    ]
