# Generated by Django 2.2.7 on 2020-06-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200315_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(blank=True, max_length=100, null=True)),
                ('lin2', models.CharField(blank=True, max_length=100, null=True)),
                ('line3', models.CharField(blank=True, max_length=100, null=True)),
                ('line4', models.CharField(blank=True, max_length=100, null=True)),
                ('line5', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('top_outer_circle_text', models.CharField(blank=True, max_length=100, null=True)),
                ('monogram_initial', models.CharField(blank=True, max_length=100, null=True)),
                ('center_text', models.CharField(blank=True, max_length=100, null=True)),
                ('bottom_outer_circle_text', models.CharField(blank=True, max_length=100, null=True)),
                ('below_arrow', models.CharField(blank=True, max_length=100, null=True)),
                ('ink_color', models.CharField(max_length=100)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_data', to='carts.CartItem')),
            ],
            options={
                'db_table': 'customization_data',
                'ordering': ('cart_item',),
            },
        ),
    ]
