# Generated by Django 2.2.7 on 2020-06-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_customizationdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizationdata',
            options={'ordering': ('cart_item',), 'verbose_name': 'Customization Data', 'verbose_name_plural': 'Customization Data'},
        ),
        migrations.RenameField(
            model_name='customizationdata',
            old_name='lin2',
            new_name='line2',
        ),
    ]
