# Generated by Django 2.2.7 on 2020-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20200608_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationdata',
            name='stamp_body',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
