# Generated by Django 2.2.7 on 2020-06-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_customizationdata_stamp_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizationdata',
            options={'ordering': ('id',), 'verbose_name': 'Customization Data', 'verbose_name_plural': 'Customization Data'},
        ),
        migrations.RemoveField(
            model_name='customizationdata',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customization_data',
            field=models.OneToOneField(blank=True, null=True, on_delete='DO NOTHONG', to='carts.CustomizationData'),
        ),
    ]
