# Generated by Django 2.2.7 on 2020-03-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='placed',
        ),
    ]
