# Generated by Django 2.2.7 on 2020-01-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200105_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work')], default='home', max_length=4),
            preserve_default=False,
        ),
    ]
