# Generated by Django 2.2.7 on 2020-01-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], max_length=4),
        ),
    ]
