# Generated by Django 2.2.7 on 2020-01-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.IntegerField(default=0),
        ),
    ]
