# Generated by Django 2.2.7 on 2020-03-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200309_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not confirmed', 'Not Confirmed'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('ready', 'Ready'), ('out for delivery', 'Out For Delivery'), ('deliverd', 'Delivered')], default='created', max_length=120),
        ),
    ]
