# Generated by Django 2.2.7 on 2020-03-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_auto_20200314_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
