# Generated by Django 2.2.7 on 2020-01-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200113_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('user',)},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('cart',)},
        ),
    ]
