# Generated by Django 2.2.7 on 2020-01-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200113_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('-created',)},
        ),
    ]
