# Generated by Django 2.2.7 on 2019-12-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_auto_20191222_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
