# Generated by Django 2.2.7 on 2020-03-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0006_auto_20200315_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
