# Generated by Django 2.2.7 on 2020-01-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0006_auto_20200112_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-updated',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-updated',), 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
