# Generated by Django 2.2.7 on 2020-06-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200315_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='carts.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not confirmed', 'Not Confirmed'), ('cancelled', 'Cancelled'), ('placed', 'Placed'), ('created', 'Created'), ('ready', 'Ready'), ('out for delivery', 'Out For Delivery'), ('deliverd', 'Delivered')], default='created', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not Paid'), ('refunded', 'Refunded'), ('cash on delivery', 'Cash On Delivery')], default='not paid', max_length=120),
        ),
    ]
